### ISSUE TITLE
Struggle isn't playable with only dazes in hand

### ISSUE THREAD

**Issue by SilentJ28** [fiiiiilth/BeakedTheCultist-StS#5]
Have 2 dazed and 1 struggle in hand.
Can't play struggle as it says "I have playable cards in hand".
I don't have medical kit or anyway to "play" the dazes.

Seems like I can never play struggle

**Comment by Moocowsgomoo** [comment]
Updated Struggle to only care about Unplayable cards (instead of "cards that cannot be played") in [the most recent version](https://github.com/fiiiiilth/BeakedTheCultist-StS/releases). It should be playable in that situation going forward.
