### ISSUE TITLE
Volatile Misfortune not retaining Burns

### ISSUE THREAD

**Issue by KongMD-Steam** [fiiiiilth/BeakedTheCultist-StS#8]
The Volatile Misfortune power does not retain Burn cards, even though they have the Unplayable modifier.

**Comment by Moocowsgomoo** [comment]
Unfortunately this is mostly an issue with the base game, where cards that activate at end of turn cannot be retained; Runic Pyramid retains Wounds but not Burns for example. I submitted this inconsistency to the developers and added an explanatory tooltip on Volatile Misfortune for now.
